# Generated by Django 3.2.9 on 2021-12-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bzu'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bzu',
            table='bzu',
        ),
    ]
